HELLO_IMAGE = api-hello:latest

run/hello:
	go run cmd/hello/hello.go

run/watermark:
	go run cmd/watermark/watermark.go

run/auth:
	go run cmd/authorization/authorization.go

run/api:
	go run api/v1/api.go